### PR TITLE
[PR] Improve support for content viewer groups

### LINKED ISSUE #3: As a plugin author, I should be able to validate groups as they are set to a post.

### PR DESCRIPTION
**Pull request by jeremyfelt**
When complete this will provide a base for plugins and themes to handle the search and assignment of content viewer groups.

Fixes #3

### CODE REVIEW

**Comment by jeremyfelt** [comment]
Ok. I think we're getting close. 😄 

@philcable can you check things out and review? No merge yet, but soon.

Of note:
- To test locally, you'll also want to use the `content-visibility` branch of WSUWP SSO Authentication: https://github.com/washingtonstateuniversity/WSUWP-Plugin-SSO-Authentication/pull/51
- To test with AD groups locally, you'll need to define `add_filter( 'wsuwp_sso_force_local_ad', '__return_true' );` in `mu-plugins/local-index.php` or similar.
- The [User Switching](https://wordpress.org/plugins/user-switching/) plugin makes testing much easier. 🎱 
- A **bunch** of code is removed. You can probably ignore all of the JS/CSS files as they are no longer needed.
- The basic class is much more simple than it used to be. It may make more sense to review that file as a whole rather than this changeset.

**Comment by philcable** [comment]
@jeremyfelt Looks good and tested out well! I might look over it one more time just for good measure.

**Comment by jeremyfelt** [comment]
- Need to rewrite tests to use new methods now that we aren't using `private` to restrict posts.
- Need to hook into the `posts_results` filter and make sure we're excluding restricted posts from public queries.
- Need to have a think about whether we should be using `private` for the post status instead to ease some of this.

**Comment by jeremyfelt** [comment]
Since the last review:
- Merge the meta box into the standard publishing actions.
- Add JSCS, JS Hint, CSS linting, etc...

In the last 5 days:
- Tried out custom post statuses
- Backed away from custom post statues
- Switched back to `private` posts rather than public
- Switched to `user_has_cap` for capabilities rather than `map_meta_cap`

@philcable Ready for another round of review! I'll explain the changes in person tomorrow. I may do one or two README commits before then.

**Comment by philcable** [comment]
@jeremyfelt This is looking good! Works great, and so far I haven't been able to break anything!

Only one thing jumped out during my first pass: the custom "Sticky" and "Password" fields need a little more work in order to function like their default counterparts. As they are, their visibility doesn't toggle - and, more importantly, they don't seem to save. Prefixing the ids of their respective span wrappers with `custom-` and updating their references in the JS to match should give us the expected toggle behavior (and help preserve the uniqueness of the ids from the default markup). As for saving, I wonder if the custom input values couldn't be assigned straight to the default hidden inputs? That could also potentially eliminate the need to provide custom hidden inputs. Last, I think there's a typo on https://github.com/washingtonstateuniversity/WSUWP-Content-Visibility/blob/fa67475a93dc4e5322f8405591b4bb7c47db70c0/js/post-admin.js#L28 (I suspect the selector should be `#sticky`).

**Comment by jeremyfelt** [comment]
Good catch. :)

After 0b572eb, sticky and password protected should be working as normal.

**Comment by jeremyfelt** [comment]
Checklist for release, hopefully tomorrow:
- [x] Add WP Document Revisions support via WSUWP Admin.
- [x] New WSUWP Admin release so that the network user filter is enabled and post type support is added for WP Document Revisions.
- [x] New WSUWP SSO Authentication release, so that the filters are prepped.
- [x] Double check WSUWP SSO Authentication in production to make sure things are still working properly.
- [x] Go over documentation, write blog post.
- [x] New WSUWP Content Visibility Release.

**Comment by jeremyfelt** [comment]
Docs written, blog post in draft, other things merged. Let's do it. :)

**Pull request merged**
